import React from 'react';

const TermsAndConditions = () => {
  return (
    <div className="terms-and-conditions bg-white">
      <h1 className="size-6">Terms of Use</h1>



<div class="max-w-4xl mx-auto px-4 py-8">
  <h2 class="text-2xl font-semibold mb-4">Terms of Use</h2>
  <p class="mb-2"><span class="font-semibold">Effective Date:</span> Feb 1, 2024</p>
  <p class="mb-4">PLEASE READ THE FOLLOWING TERMS OF USE CAREFULLY. THESE TERMS OF USE GOVERN YOUR USE OF THE EARN BY PLAY WEBSITE (EARNBYPLAY.COM) (“SITE”) AND ALL SERVICES OFFERED THROUGH THE SITE INCLUDING HOW DISPUTES BETWEEN US WILL BE HANDLED AS DESCRIBED BELOW...</p>
  
  <h3 class="text-xl font-semibold mb-2">Acceptance of Terms of Use</h3>
  <p class="mb-4">This Agreement is an electronic contract that sets out the legally binding terms ("Terms") of your use of the Site and the membership services available to you on the Site ("Services"). This Agreement includes Earn by Play’s membership policies and notices about use of its Site and Services...</p>
  
  <h3 class="text-xl font-semibold mb-2">Updates to Terms</h3>
  <p class="mb-4">Earn by Play reserves the right to update or change these Terms at any time by posting the most current version of the Terms on the Site. Earn by Play will provide notice of changes to the Terms by posting the new Terms on the Site with a new Effective Date shown...</p>

  <h3 class="text-xl font-semibold mb-2">Electronic Form</h3>
  <p class="mb-4">By accessing the Site or becoming a member of Earn by Play ("Member"), you consent to have this Agreement provided to you in electronic form. </p>

  {/* <h3 class="text-xl font-semibold mb-2">
  </h3> <p class="mb-4"> */}

  <h3 class="text-xl font-semibold mb-2"> Non-electronic Copy.</h3>
  <p class="mb-4"> You have the right to receive this Agreement in non-electronic form. You may request a non-electronic copy of this Agreement either before or after you electronically sign the Agreement. To receive a non-electronic copy of this Agreement, please contact us online or send a letter and self-addressed stamped envelope to: PivotPoint Technologies Inc., 438 King St West, Unit 815, Toronto, Canada, M5V3T9.</p>
  <h3 class="text-xl font-semibold mb-2"> Registering as a Member.</h3> <p class="mb-4"> You do not have to be an Earn by Play Member to view benefits available through this Site, but only approved Members can access the Earn by Play features and Services. By registering and being accepted as a Member, you agree to (i) provide true, accurate, current, and complete information about yourself as prompted by the registration form, and (ii) maintain and properly update your account information to keep it true, accurate, current, and complete, and (iii) use the Service solely for your individual, personal use and not for commercial purposes or in connection with a business. If you provide information that is untrue, inaccurate, not current, or incomplete, or if we have reasonable grounds to suspect that you have, or you violate these Terms, as determined in our sole discretion, we have the right to suspend or terminate your membership and refuse any and all current or future use of the Site and the Services (or any portion thereof). Registration is currently available only to consumers (not businesses) for their individual personal use residing in the United States only, subject to Earn by Play's verification, in its sole discretion. Without limitation of the foregoing, Earn by Play reserves the right to reject any Membership application in its sole discretion. Your membership term is also your billing term. . We reserve the right at any time and in our sole discretion to verify a Member’s eligibility and compliance with these Terms prior to fulfilling any membership Service, including, but not limited to, ensuring that the Member is not using the Services for business or commercial purposes. There is a limit of one membership and one introductory/premium offer per household.</p>
  <h3 class="text-xl font-semibold mb-2"> Membership, Subscriptions; Charges on Your Billing Account.</h3> 
  <h3 class="text-xl font-semibold mb-2"> </h3> <p class="mb-4">Earn by Play charges you for your access to the Service using the billing information you provide (your "Billing Account") at the time of enrollment. By enrolling in Earn by Play, You authorize Earn by Play to charge your Billing Account the fees then in effect for the Service. Earn by Play reserves the right to correct any errors or mistakes that it makes, even if it has already requested or received payment, and to update your information from available third-party sources. All membership fees and cash back earnings are in US Dollars.</p>
  <h3 class="text-xl font-semibold mb-2"> Recurring Billing. </h3> <p class="mb-4">Access to the Service requires a subscription for membership and may consist of an initial period, where you can try the Services for free or for an introductory paid trial, followed by recurring period charges authorized and agreed to by you at the time of your subscription. If your membership subscription has an initial and recurring payment feature, you accept responsibility for all recurring charges prior to cancellation. To change or cancel your membership at any time, go to the "Manage Membership" page under the “More” tab, or send your request to us using the "Support" link on any page of the Site. Unless cancelled, your membership will be automatically extended for successive renewal periods of the same duration as the membership term originally selected, at the then-current non-promotional membership rate. If you cancel a monthly membership, you are eligible for a refund of your first monthly bill, and you will immediately lose access to your membership and its benefits even if you still have days left until the end of your then-current membership term. However, you won't be eligible for a prorated refund of any portion of the monthly membership fee paid thereafter for the then-current membership period. If you believe you are owed a refund, please contact our support team under the “Support” tab. If you cancel your membership but want to become a member again, you should be able to do that through the “Subscribe” button on several pages of the site. Your non-termination or continued use of the Service reaffirms that Earn by Play is authorized to charge your Payment Method on the recurring basis you agreed to upon enrollment. Earn by Play may submit those charges for payment, and you will be responsible for such charges. EARN BY PLAY MAY SUBMIT PERIODIC CHARGES WITHOUT FURTHER AUTHORIZATION FROM YOU, UNTIL YOU AFFIRMATIVELY CANCEL YOUR MEMBERSHIP OR NOTIFY US THAT YOU WISH TO CHANGE YOUR PAYMENT METHOD. SUCH NOTICE WILL NOT AFFECT CHARGES SUBMITTED BEFORE EARN BY PLAY REASONABLY COULD ACT. TO TERMINATE YOUR AUTHORIZATION OR CHANGE YOUR PAYMENT METHOD, VISIT THE "SUPPORT" PAGE UNDER THE “MORE” TAB ON THE SITE AND SEND YOUR REQUEST TO US.</p>
  <h3 class="text-xl font-semibold mb-2"> Current Information Required. </h3> <p class="mb-4">YOU MUST PROMPTLY NOTIFY EARN BY PLAY IF YOUR PAYMENT METHOD IS CANCELLED (E.G., FOR LOSS OR THEFT) OR IF YOU BECOME AWARE OF A POTENTIAL BREACH OF SECURITY, SUCH AS THE UNAUTHORIZED DISCLOSURE OR USE OF YOUR PHONE NUMBER. CHANGES TO SUCH INFORMATION CAN BE MADE IN THE "SUPPORT" PAGE UNDER THE “MORE” TAB OF THE SITE. IF YOU FAIL TO PROVIDE EARN BY PLAY ANY OF THE FOREGOING INFORMATION, YOU AGREE THAT EARN BY PLAY MAY CONTINUE CHARGING YOU FOR ANY USE OF THE SERVICE UNDER YOUR BILLING ACCOUNT, UNLESS WE HAVE EVIDENCE THAT YOU HAVE TERMINATED YOUR MEMBERSHIP FOR THE SERVICE.</p>
  <h3 class="text-xl font-semibold mb-2"> Payment Method. </h3> <p class="mb-4">The terms of your payment will be based on your Payment Method and may be determined by agreements between you and the financial institution, credit card issuer, or other provider of your chosen Payment Method (the "Payment Method Provider"). If Earn by Play does not receive payment from your Payment Method Provider, you agree to pay all amounts due on your Billing Account upon demand.</p>
  <h3 class="text-xl font-semibold mb-2"> Change in Amount Authorized. </h3> <p class="mb-4">If the amount to be charged to your Billing Account varies from the current rate set forth in your initial offer due to an increase in our current rates (other than due to the imposition or change in the amount of state sales taxes), Earn by Play shall provide notice of the amount to be charged and the date of the charge at least 10 days before the scheduled date of the transaction. Any agreement you have with your Payment Method Provider will govern your use of your Payment Method. You agree that Earn by Play may accumulate charges incurred and submit them as one or more aggregate charges during or at the end of each billing cycle.</p>
  <h3 class="text-xl font-semibold mb-2"> Free and Introductory Trials and Other Promotions. </h3> <p class="mb-4">Any free or introductory paid trial offer or other promotion that provides membership access to the Service must be used within the specified time of the trial. You must cancel your membership before the end of the stated trial period in order to avoid being charged the full membership fee set forth in the offer terms. Your trial period begins on the day you accept the trial offer; for example, if you accept a 7-day trial offer, your full paid membership term will begin one week from the date that you accepted the offer unless you cancel. All trial-period and/or promotional offers that refer to a start time and/or deadline use Eastern Time Zone (ET) hours; e.g., if promotional material says that an offer will end at midnight on a certain date, that should be interpreted to mean that it will end at midnight ET on that date. There is a limit of one membership and one introductory/premium offer per household.</p>
  <h3 class="text-xl font-semibold mb-2"> How You Can Use the Services. </h3> <p class="mb-4">This Site and the Services offered are intended for your individual, personal use in accordance with these Terms. Use of this Site and the Services for commercial purposes or in connection with a business is a violation of these Terms. You agree that you will not (i) copy, display, or distribute any part of the Site, in any medium, without Earn by Play's prior written consent, or (ii) alter or modify any part of the Site other than as may be reasonably necessary to use the Site for its intended purpose. You further agree that you will not use any automated devices, such as spiders, robots, or data-mining techniques, to catalog, download, store, or otherwise reproduce, store, or distribute content available on the Site, manipulate the Site or the Services, or otherwise exceed the limited access granted to you by Earn by Play. You will take no action to interfere with, interrupt, destroy, or limit the functionality of the Site or any computer software or hardware or telecommunications equipment. You will not distribute or transmit any content or software or other computer files that contain a computer virus or other harmful component. At this time, the Services are only available to residents of the United States, its territoriesand those consumers with APO/FPO addresses.</p>
  <h3 class="text-xl font-semibold mb-2"> User Submissions. </h3> <p class="mb-4">By submitting content to the Site, for instance, in the form of a testimonial ("User Content"), you grant to Earn by Play and its licensees and successors in business a perpetual, worldwide, royalty-free, and non-exclusive license to reproduce, distribute, modify, edit, display, adapt, create derivative works from, market, and promote the User Content for any commercial purposes, and in any medium now existing or hereinafter developed, and to use your name, likeness, and any personal information you submit with the Use Content without your prior approval or the payment of any compensation.</p>
  <h3 class="text-xl font-semibold mb-2"> Proprietary Rights. </h3> <p class="mb-4">The Site and all material published on the Site, including but not limited to text, photographs, video, text, graphics, music, sounds, messages, comments, ratings, and other materials, is owned by Earn by Play or its licensors and is protected by copyright, patents, trademarks, trade secrets, and/or other proprietary rights, including under the United States copyright laws. Earn by Play owns a copyright in the selection, coordination, arrangement, and enhancement of such content and a copyright in the Site. Earn by Play and its logos are trademarks of PivotPoint Technologies Inc., and are protected by state and federal laws. All other trademarks appearing on this Site ("Marks") are trademarks of their respective owners, including Earn by Play and its marketing partners. Users are prohibited from using any Marks without the written permission of Earn by Play or such third party that may own the Marks. You may not copy, publish, transmit, distribute, perform, sell, create derivative works of, or in any way exploit any of the content, in whole or in part, without Earn by Play's prior written consent. You agree not to reproduce, duplicate, copy, sell, resell, or exploit for any commercial purposes any aspect of the Site or Service. You acknowledge that you do not acquire any ownership rights by downloading copyrighted material. You may download content for your personal, non-commercial use only as provided in these Terms, provided that you keep intact all copyright and other proprietary notices. Copying or storing of content for other than personal use is expressly prohibited without prior permission from us or the copyright holder identified in the copyright notice contained in the content.</p>
  <h3 class="text-xl font-semibold mb-2"> No License Granted. </h3> <p class="mb-4">Except for allowing you to use the Site and Services for your personal use as set forth in the paragraph above, when you use the Site or Services, you are not receiving a license or any other rights from us, including intellectual property or other proprietary rights of Earn by Play. You understand that you have no rights to the Services or any other Earn by Play property except as we indicate in these Terms.</p>
  <h3 class="text-xl font-semibold mb-2"> Money Movement. </h3> <p class="mb-4">The accrual of rewards by the user is facilitated through engagements with various affiliates or reward partners, including, but not limited to, prodege.com and ayetstudios.com. Said rewards shall be credited to the user's Earn By Play wallet. The user retains the right to redeem the accumulated rewards from their wallet either through (a) gift cards, which are wholly administered by our designated gift card facilitator, Runa.io, or (b) monetary disbursements via PayPal.</p>
  <h3 class="text-xl font-semibold mb-2"> Age Requirements. </h3> <p class="mb-4">You must be at least 18 years old or the age of majority in your state of residence, whichever is older, to join Earn by Play and to use the Services.</p>
  <h3 class="text-xl font-semibold mb-2"> Limit on earnings in a 24-hour period. </h3> <p class="mb-4">The maximum a user is able to earn in a 24-hour period is $1500.</p>
  <h3 class="text-xl font-semibold mb-2"> Communications from Earn by Play. </h3> <p class="mb-4">By registering for Earn by Play, you will receive online communications from Earn by Play. You may also receive electronic communications from Earn by Play by just providing your phone number and not registering. In either case, to unsubscribe from any Earn by Play email list, simply click on the "Unsubscribe" link at the bottom of the email, and your name will be removed from that mailing list. To see how we use your personal information, please refer to our Privacy Policy.</p>
  <h3 class="text-xl font-semibold mb-2"> Links. </h3> <p class="mb-4">You may be able to access other websites or resources through links on the Site. Because Earn by Play has no control over such sites and resources, you acknowledge and agree that Earn by Play is not responsible for the availability of such external sites or resources, and does not endorse and is not responsible or liable for any content, advertising, products, or other materials available from such sites or resources. You further acknowledge and agree that Earn by Play shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods, or services available on or through any such site or resource.</p>
  <h3 class="text-xl font-semibold mb-2"> Indemnity/Release. </h3> <p class="mb-4">You understand that you are personally responsible for your behavior while on the Site and agree to indemnify and hold Earn by Play, and its affiliates, business partners, and suppliers, and their respective officers, directors, employees, and agents, harmless from and against any loss, damage, liability, cost, or expense of any kind (including attorneys' fees) that we may incur arising out of or related to any products or services purchased by you in connection with the Site or the Services and in connection with a third-party claim or otherwise, in relation to your use of the Services or access to the Site, or your violation of either these Terms, applicable law, or the rights of any third party. You are solely responsible for your own interactions with any merchants accessed through the Site or Services. To the extent permitted under applicable laws, you hereby release Earn by Play, and its affiliates, business partners, and suppliers from any and all claims or liability related to any product or service of a merchant, any action or inaction by a merchant, including any merchant's failure to comply with applicable law and/or failure to abide by the Services Terms and any conduct or speech, whether online or offline, of any other user.</p>
  <h3 class="text-xl font-semibold mb-2"></h3> <p> In connection with the foregoing release, you hereby waive California Civil Code Section 1542 (and any similar provision in any other jurisdiction), which states: "A general release does not extend to claims which the creditor does not know or suspect to exist in his or her favor at the time of executing the release, which, if known by him or her must have materially affected his or her settlement with the debtor."</p>
  <h3 class="text-xl font-semibold mb-2"> Disclaimer of Warranties. </h3> <p class="mb-4">YOU UNDERSTAND THAT YOUR USE OF THE SITE AND SERVICES (INCLUDING ANY DOWNLOADS OR ANY LOSS OF DATA OR OTHER DAMAGE TO YOUR COMPUTER SYSTEM OR PHONE YOU EXPERIENCE FROM USING THE SITE AND SERVICES) IS AT YOUR SOLE RISK. YOU UNDERSTAND THAT THE SITE AND SERVICES AND ALL INFORMATION, PRODUCTS, AND OTHER CONTENT (INCLUDING THIRD-PARTY INFORMATION, PRODUCTS, AND CONTENT) INCLUDED IN OR ACCESSIBLE FROM THE SITE OR SERVICES, ARE PROVIDED ON AN "AS IS," "WHERE IS," AND "WHERE AVAILABLE" BASIS, AND ARE SUBJECT TO CHANGE AT ANY TIME WITHOUT NOTICE TO YOU. YOU ACKNOWLEDGE THAT EARN BY PLAY AND ITS AFFILIATES, BUSINESS PARTNERS AND SUPPLIERS , MAKES NO WARRANTY THAT THE SITE OR SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE. YOU UNDERSTAND THAT YOUR USE OF AND ACCESS TO THE SERVICES MAY BE AFFECTED BY THIRD PARTY ACTS AND OMISSIONS THAT ARE BEYOND EARN BY PLAY’S AND ITS AFFILIATES, BUSINESS PARTNERS AND SUPPLIERS CONTROL AND THAT EARN BY PLAY AND ITS AFFILIATES, BUSINESS PARTNERS AND SUPPLIERS  WILL NOT BE RESPONSIBLE FOR YOUR ACCESS TO OR INABILITY TO ACCESS AND ENJOY THE SERVICES DUE TO SUCH THIRD PARTY ACTIONS. YOU UNDERSTAND THAT EARN BY PLAY AND ITS AFFILIATES, BUSINESS PARTNERS AND SUPPLIERS  DO NOT WARRANT THAT THE RESULTS OBTAINED FROM YOUR USE OF THE SITE OR SERVICES WILL MEET YOUR EXPECTATIONS. NO WARRANTY OF ANY KIND, WHETHER ORAL OR WRITTEN, CAN MODIFY THE TERMS OF THE DISCLAIMER SET FORTH IN THIS DOCUMENT. YOUR USE AND BROWSING OF THE SITE IS AT YOUR OWN RISK. IF YOU ARE DISSATISFIED WITH ANY OF THE MATERIALS CONTAINED IN THE SITE OR SERVICES, OR WITH ANY OF THESE TERMS, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE ACCESSING AND USING THE SITE AND SERVICES. TO THE FULLEST EXTENT PERMITTED BY LAW, EARN BY PLAY AND ITS AFFILIATES, BUSINESS PARTNERS AND SUPPLIERS DISCLAIM ALL REPRESENTATIONS, WARRANTIES, AND CONDITIONS OF ANY KIND (EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT OF PROPRIETARY RIGHTS) AS TO THE SITE AND SERVICES AND ALL INFORMATION, PRODUCTS, AND OTHER CONTENT (INCLUDING THIRD-PARTY INFORMATION, PRODUCTS, AND CONTENT) INCLUDED IN OR ACCESSIBLE FROM THE SITE AND SERVICES.</p>
  <h3 class="text-xl font-semibold mb-2"> </h3> <p> ALL CONTENT, PRODUCTS, AND THIRD-PARTY SERVICES ON THE SITE, OR OBTAINED FROM A WEBSITE TO WHICH THE SITE IS LINKED, ARE PROVIDED TO YOU "AS IS," WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, SECURITY, OR ACCURACY. EARN BY PLAY AND ITS AFFILIATES, BUSINESS PARTNERS AND SUPPLIERS DO NOT ENDORSE AND ARE NOT RESPONSIBLE FOR THE MERCHANTABLITY OF ANY PRODUCT OR SERVICE ACCESSED FROM THE SITE OR A LINKED SITE. OTHER THAN AS REQUIRED BY LAW, UNDER NO CIRCUMSTANCE WILL EARN BY PLAY AND ITS AFFILIATES, BUSINESS PARTNERS AND SUPPLIERS BE LIABLE FOR ANY LOSS OR DAMAGE CAUSED BY YOUR RELIANCE ON INFORMATION OBTAINED THROUGH THE SITE OR A LINKED SITE, OR YOUR RELIANCE ON ANY PRODUCT OR SERVICE OBTAINED FROM THE SITE OR A LINKED SITE.</p>
  <h3 class="text-xl font-semibold mb-2"> Liability Limitation. </h3> <p class="mb-4"> TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL EARN BY PLAY OR ITS AFFILIATES, BUSINESS PARTNERS OR SUPPLIERS BE LIABLE TO YOU (OR ANY THIRD PARTY MAKING CLAIMS THROUGH YOU) FOR ANY DAMAGES WHATSOEVER, INCLUDING BUT NOT LIMITED TO ANY DIRECT, INDIRECT, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR INCIDENTAL DAMAGES, OR DAMAGES FOR LOSS OF USE, PROFITS, DATA, OR OTHER INTANGIBLES, OR THE COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, UNAUTHORIZED ACCESS TO AND TAMPERING WITH YOUR PERSONAL INFORMATION OR TRANSMISSIONS, ARISING OUT OF OR RELATED TO THE USE, INABILITY TO USE, UNAUTHORIZED USE, PERFORMANCE, OR NON-PERFORMANCE OF THE SITE OR THE SERVICES, EVEN IF EARN BY PLAY HAS BEEN ADVISED PREVIOUSLY OF THE POSSIBILITY OF SUCH DAMAGES AND WHETHER SUCH DAMAGES ARISE IN CONTRACT, NEGLIGENCE, TORT, UNDER STATUTE, IN EQUITY, AT LAW, OR OTHERWISE. UNLESS LIMITED OR MODIFIED BY APPLICABLE LAW, THE FOREGOING DISCLAIMERS, WAIVERS, AND LIMITATIONS SHALL APPLY TO THE MAXIMUM EXTENT PERMITTED, EVEN IF ANY REMEDY FAILS ITS ESSENTIAL PURPOSE. EARN BY PLAY'S LICENSORS AND CONTRACTORS ARE INTENDED THIRD-PARTY BENEFICIARIES OF THESE DISCLAIMERS. IF ANY PART OF THESE WARRANTY DISCLAIMERS OR LIMITATIONS OF LIABILITY IS FOUND TO BE INVALID OR UNENFORCEABLE FOR ANY REASON, THEN EARN BY PLAY'S OR ITS AFFILIATES’, BUSINESS PARTNERS’ OR SUPPLIERS’ AGGREGATE LIABILITY FOR ALL CLAIMS UNDER SUCH CIRCUMSTANCES FOR LIABILITIES SHALL NOT EXCEED TEN DOLLARS ($10).</p>
  <h3 class="text-xl font-semibold mb-2"> Termination.  </h3> <p class="mb-4">We can suspend or terminate your Membership in Earn by Play and your access to the Site or the Services, in whole or in part, at any time, immediately and without notice if, at Earn by Play's sole discretion, you fail to comply with any of these Terms of Use or Terms of Service. Upon termination, you must destroy all materials obtained from this Site and the Services and all copies thereof. In the event of suspension or termination, you are no longer authorized to access the Site or the Services, and the restrictions imposed on you with respect to any materials downloaded from the Site or the Services and the disclaimers and limitations of liabilities set forth in the Terms shall survive.</p>
  <h3 class="text-xl font-semibold mb-2"> Access to Services.  </h3> <p class="mb-4">You understand and agree that your membership in Earn by Play is subject to and conditioned upon the following: Your continued adherence to these Terms and any future modifications thereto and compliance with the Terms of Service. Your violation of these Terms of Use or any other agreement between you and Earn by Play constitutes grounds for immediate termination of your membership without further notice, at our sole discretion. We may also terminate your membership at any time, immediately and without notice, if we determine, in our sole discretion, that your conduct is detrimental to our business or the Earn by Play community. Termination of your Membership will result in cancellation of all rights of access and use of Services granted to Members, and cancelled Members may be denied access to Services or re-enrollment as Members. Earn by Play reserves the right to change, discontinue, or suspend Earn by Play or any of the Services at any time for any reason. Members may terminate their Membership at any time using the "Manage Membership" page under the “More” tab of the Site. Earn by Play shall be the sole determiner in cases of suspected abuse, fraud, or breach of these Terms of Use or Terms of Service. Any decision Earn by Play makes relating to termination or suspension of any Member's account shall be final and binding. You agree that we may terminate, modify, discontinue, or abandon the Site or Services with or without notice to you and that we will not be liable to you or any third party as a result of such termination, modification, discontinuance, or abandonment. If this Agreement is terminated for any reason, the provisions titled Proprietary Rights, No License Granted, Indemnity/Release, Disclaimer of Warranties, Liability Limitation, Access To Services, Termination, Privacy, Governing Law/Disputes, and Miscellaneous shall survive any such termination. At this time, the Services are only available to residents of the United States, its territories, and those consumers with APO/FPO addresses. </p>
  <h3 class="text-xl font-semibold mb-2"> Privacy.  </h3> <p class="mb-4">This Site is governed by the terms and conditions set out in our privacy policy found at XXXXX, which is incorporated herein by reference.</p>
  <h3 class="text-xl font-semibold mb-2"> Conditions of Service.  </h3> <p class="mb-4">Your use of the benefits available through your membership and the Services are also governed by the Terms of Service, which are incorporated herein by reference. In the event of any conflict in these Terms of Use and the Terms of Service, these Terms of Use will control.</p>
  <h3 class="text-xl font-semibold mb-2"> No Third-Party Beneficiaries.  </h3> <p class="mb-4">You agree that, except as otherwise expressly provided in this Agreement, there shall be no third-party beneficiaries to this Agreement.</p>
  <h3 class="text-xl font-semibold mb-2"> Dispute Resolution:</h3><p> Agreement to Arbitrate Disputes, Waiver of Class Arbitration, Governing Law, Enforcement of Arbitration Award, Severability, and Jurisdiction.</p>
  <h3 class="text-xl font-semibold mb-2"> </h3> <p>Agreement to Arbitrate Disputes:</p>
  <h3 class="text-xl font-semibold mb-2"></h3> <p> INSTEAD OF SUING IN COURT, YOU AND WE EACH AGREE TO ARBITRATE DISPUTES ON A BILATERAL (INDIVIDUAL) BASIS. Any and all disputes, controversies, demands, counts, claims, or causes of action between you and Earn by Play (including, but not limited to, disputes related in any way to the interpretation and scope of this clause, Terms of Use, Terms of Service, and Privacy Policy, your use of the Site and Services, and the arbitrability of the dispute) must exclusively be settled through binding and confidential arbitration. THERE'S NO JUDGE OR JURY IN ARBITRATION, PROCEDURES FOR ARBITRATION ARE SIMPLER AND MORE LIMITED THAN RULES APPLICABLE IN COURT, AND REVIEW BY A COURT IS LIMITED.</p>
  <h3 class="text-xl font-semibold mb-2"> </h3><p>Arbitration will be subject to the Federal Arbitration Act and must be conducted by the American Arbitration Association (AAA) before one commercial arbitrator. The conduct of the arbitration will be subject to AAA's then-current rules and procedures for consumer arbitration (currently titled “Consumer Arbitration Rules”) (collectively, “Rules and Procedures”). YOU SPECIFICALLY AGREE YOU ARE BOUND TO RESOLVE ALL DISPUTES IN ARBITRATION, AND YOU ACKNOWLEDGE YOU ARE VOLUNTARILY AND KNOWINGLY FORFEITING YOUR RIGHT TO A TRIAL BY JURY AND TO OTHERWISE PROCEED IN A LAWSUIT IN STATE OR FEDERAL COURT. Payment of arbitration costs will be governed by AAA's fee schedule, unless you are able to show that your portion will be prohibitive as compared to litigation costs, in which case Earn by Play will pay as much of your arbitration costs as the arbitrator deems necessary to prevent the arbitration from being cost-prohibitive as compared to litigation costs. Earn by Play also reserves the right, in its sole and exclusive discretion, to assume responsibility for all arbitration costs imposed by AAA. Each party agrees to pay its own attorneys' fees and expenses unless there is a governing statutory provision or remedy under the governing law that requires the prevailing party to be paid attorneys' fees and expenses.</p>
  <h3 class="text-xl font-semibold mb-2"> </h3><p>Information on AAA, its Rules and Procedures, and how to start arbitration can be found at http://www.adr.org or by calling 800-778-7879.</p>
  <h3 class="text-xl font-semibold mb-2"> </h3><p>Notwithstanding the foregoing, to the extent the dispute arises from a violation of your or Earn by Play's intellectual property rights in any manner, both parties agree the non-infringing party may seek injunctive remedies (or an equivalent type of urgent legal relief) in a state or federal court consistent with the Governing Law and Jurisdiction subsections below, and both parties consent to exclusive jurisdiction and venue in such courts. Additionally, you or Earn by Play may take the dispute to small claims court if the dispute qualifies for small claims court.</p>
  <h3 class="text-xl font-semibold mb-2"> Waiver of Class Arbitration:</h3><p> To the fullest extent permissible under applicable law, all disputes must be resolved by binding confidential arbitration on an individual basis. You expressly agree that no other disputes will be consolidated or joined with your dispute, whether through class arbitration proceedings or otherwise. You further acknowledge and agree any arbitrator assigned to a dispute must not and lacks the authority to conduct class arbitration proceedings or award class-wide relief and that such arbitrator must only hear your individual dispute. You acknowledge you are voluntarily and knowingly waiving any right to participate as a representative of any class of claimants pertaining to any dispute subject to arbitration, such that you will not be entitled to arbitrate any dispute as a representative plaintiff or claimant, class representative, class member, or private attorney general.</p>
  <h3 class="text-xl font-semibold mb-2"> Governing Law: </h3><p>These Terms and all disputes between the parties will be governed in all respects by the laws of the State of Connecticut, consistent with the Federal Arbitration Act, as they apply to agreements entered into and to be performed entirely within Connecticut between Connecticut residents, without regard to any conflict-of-law provisions. Further, in any arbitration, both parties agree the arbitrator must honor claims of privilege and privacy recognized under Connecticut law.</p>
  <h3 class="text-xl font-semibold mb-2"> </h3><p>Enforcement of Arbitration Award: The arbitrator's award will be final and binding on all parties and may be entered as a judgment in any court of competent jurisdiction.</p>
  <h3 class="text-xl font-semibold mb-2"> Severability:</h3><p> If any portion of this Dispute Resolution section (with the exception of the Waiver of Class Arbitration subsection) is deemed invalid or unenforceable by any arbitrator or court of competent jurisdiction, the invalid or unenforceable portion must be severed and removed from the Terms, and the remaining portions (including the Agreement to Arbitrate Disputes subsection) will remain binding on you and Earn by Play. If any arbitrator deems the Waiver of Class Arbitration subsection to be invalid or unenforceable, then the entire Agreement to Arbitrate Disputes subsection will be null and void. Under such circumstances, you expressly acknowledge and agree that the Governing Law and Jurisdiction subsections apply to any disputes between you and Earn by Play, and both parties consent to exclusive jurisdiction and venue in such courts.</p>
  <h3 class="text-xl font-semibold mb-2"> Jurisdiction: </h3><p>If, in any dispute, the Agreement to Arbitrate Disputes subsection is determined to be invalid or unenforceable, notwithstanding the Severability subsection above, or null and void by any arbitrator or court of competent jurisdiction, or if the dispute seeks injunctive remedies arising from a violation of your or Earn by Play's intellectual property rights, the dispute must be resolved by a state or federal court located in Hartford County, Connecticut, USA. The parties agree to submit to the personal jurisdiction of such Connecticut state or federal courts for the purposes of litigating any such dispute. This subsection does not apply to disputes made in small claims court.</p>
  <h3 class="text-xl font-semibold mb-2"> Miscellaneous. </h3><p>These Terms and policies incorporated herein are the entire agreement between you and Earn by Play. They supersede any and all prior or contemporaneous agreements between you and Earn by Play relating to your use of the Site or the Services. If any part of these Terms is determined to be invalid or unenforceable, it will not impact any other provision of these Terms, all of which will remain in full force and effect. The failure of Earn by Play to partially or fully exercise any rights, or the waiver of Earn by Play of any breach of these Terms by you, shall not prevent a subsequent exercise of such right by Earn by Play or be deemed a waiver by Earn by Play of any subsequent breach by you of the same or any other term of these Terms. The rights and remedies of Earn by Play under these Terms and any other applicable agreement between you and Earn by Play shall be cumulative, and the exercise of any such right or remedy shall not limit Earn by Play's right to exercise any other right or remedy.</p>
  <h3 class="text-xl font-semibold mb-2"> </h3><p>THE TERMS OF USE SET FORTH ABOVE AND TERMS OF SERVICE MAY CHANGE WITHOUT NOTICE.</p>
</div>






    </div>
  );
};

export default TermsAndConditions;
